"""Initial schema with multi-tenant support

Revision ID: 54c6d18ecdb8
Revises: 
Create Date: 2025-11-25 11:12:13.910742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c6d18ecdb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('subscription_plan', sa.Text(), nullable=True),
    sa.Column('billing_email', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('review_mode', sa.Text(), nullable=True),
    sa.Column('confidence_threshold', sa.REAL(), nullable=True),
    sa.Column('auto_upload_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.Text(), nullable=True),
    sa.Column('price_per_document', sa.REAL(), nullable=True),
    sa.Column('monthly_base_fee', sa.REAL(), nullable=True),
    sa.Column('monthly_document_limit', sa.Integer(), nullable=True),
    sa.Column('overage_price_per_document', sa.REAL(), nullable=True),
    sa.Column('stripe_customer_id', sa.Text(), nullable=True),
    sa.Column('stripe_subscription_id', sa.Text(), nullable=True),
    sa.Column('billing_cycle_start', sa.Date(), nullable=True),
    sa.Column('current_period_start', sa.Date(), nullable=True),
    sa.Column('current_period_end', sa.Date(), nullable=True),
    sa.Column('trial_end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth0_user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth0_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('batches',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=True),
    sa.Column('successful', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('processing_summary_json', sa.Text(), nullable=True),
    sa.Column('download_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connector_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connector_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_used_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('extracted_data', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.REAL(), nullable=True),
    sa.Column('connector_type', sa.Text(), nullable=True),
    sa.Column('connector_config_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('uploaded_to_connector', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('connector_type', sa.Text(), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('review_mode', sa.Text(), nullable=True),
    sa.Column('confidence_threshold', sa.REAL(), nullable=True),
    sa.Column('auto_upload_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('billed', sa.Boolean(), nullable=True),
    sa.Column('billing_period', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('original_confidence', sa.REAL(), nullable=True),
    sa.Column('correction_method', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document_metadata.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connector_config_id', sa.Integer(), nullable=False),
    sa.Column('source_field', sa.VARCHAR(length=255), nullable=False),
    sa.Column('target_field', sa.VARCHAR(length=255), nullable=False),
    sa.Column('confidence_score', sa.REAL(), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['connector_config_id'], ['connector_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_mappings')
    op.drop_table('field_corrections')
    op.drop_table('usage_logs')
    op.drop_table('organization_settings')
    op.drop_table('document_metadata')
    op.drop_table('connector_configs')
    op.drop_table('batches')
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_table('organizations')
    # ### end Alembic commands ###
